//! Output formats: emit a rendered banner as terminal output, raw text, or a
//! ready-to-paste snippet for another language.
//!
//! The snippet formats let you generate a banner once and embed it directly in
//! your own tool's source — a splash for `--help`, a startup logo, etc.

/// A target output format for a rendered banner.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Format {
    /// Colored terminal output (color auto-detected: on for a TTY, off when piped).
    Term,
    /// Raw ANSI string, color forced on — for capturing colored bytes.
    Ansi,
    /// Plain glyphs, no color.
    Raw,
    /// A Rust `const` snippet.
    Rust,
    /// A Go `const` snippet.
    Go,
    /// A Python string snippet.
    Python,
    /// A POSIX shell heredoc snippet.
    Shell,
    /// A standalone SVG image.
    Svg,
    /// A standalone HTML document (a `<pre>` of colored spans).
    Html,
}

impl Format {
    pub fn parse(s: &str) -> Result<Format, String> {
        match s.to_ascii_lowercase().as_str() {
            "term" | "terminal" => Ok(Format::Term),
            "ansi" => Ok(Format::Ansi),
            "raw" | "text" | "txt" => Ok(Format::Raw),
            "rust" | "rs" => Ok(Format::Rust),
            "go" | "golang" => Ok(Format::Go),
            "python" | "py" => Ok(Format::Python),
            "shell" | "sh" | "bash" => Ok(Format::Shell),
            "svg" => Ok(Format::Svg),
            "html" | "htm" => Ok(Format::Html),
            _ => Err(format!(
                "unknown format: {s} (term|ansi|raw|rust|go|python|shell|svg|html)"
            )),
        }
    }

    /// Whether this format bakes color into its output regardless of TTY.
    pub fn forces_color(self) -> bool {
        matches!(
            self,
            Format::Ansi | Format::Rust | Format::Go | Format::Python | Format::Shell
        )
    }

    /// Whether this format is a code/text snippet (vs. direct terminal output).
    pub fn is_snippet(self) -> bool {
        matches!(
            self,
            Format::Rust | Format::Go | Format::Python | Format::Shell
        )
    }
}

/// Wrap a painted banner in the chosen snippet format. For non-snippet formats
/// (`Term`, `Ansi`, `Raw`) the painted string is returned unchanged.
pub fn wrap(format: Format, painted: &str) -> String {
    match format {
        // Svg/Html are rendered separately (not from painted ANSI); fallback.
        Format::Term | Format::Ansi | Format::Raw | Format::Svg | Format::Html => {
            painted.to_string()
        }
        Format::Rust => format!(
            "// Generated by sigil. Print with: print!(\"{{BANNER}}\");\n\
             pub const BANNER: &str = \"{}\";\n",
            escape_c_like(painted)
        ),
        Format::Go => format!(
            "// Generated by sigil. Print with: fmt.Print(Banner)\n\
             const Banner = \"{}\"\n",
            escape_c_like(painted)
        ),
        Format::Python => format!(
            "# Generated by sigil. Print with: print(BANNER, end=\"\")\n\
             BANNER = \"{}\"\n",
            escape_c_like(painted)
        ),
        Format::Shell => format!(
            "# Generated by sigil. Prints a banner (contains ANSI color codes).\n\
             cat <<'SIGIL_BANNER'\n{}SIGIL_BANNER\n",
            painted
        ),
    }
}

/// Escape a string for a double-quoted C-like literal (Rust/Go/Python).
///
/// Keeps printable Unicode (block glyphs, box drawing) literal; encodes the
/// escape byte, quotes, backslashes, and newlines.
fn escape_c_like(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 16);
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\x1b' => out.push_str("\\x1b"),
            c => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_aliases() {
        assert_eq!(Format::parse("rs").unwrap(), Format::Rust);
        assert_eq!(Format::parse("PY").unwrap(), Format::Python);
        assert_eq!(Format::parse("bash").unwrap(), Format::Shell);
        assert!(Format::parse("cobol").is_err());
    }

    #[test]
    fn escapes_ansi_and_quotes() {
        let painted = "\x1b[38;2;1;2;3mA\"B\\C\x1b[0m\n";
        let e = escape_c_like(painted);
        assert!(e.contains("\\x1b[38;2;1;2;3m"));
        assert!(e.contains("A\\\"B\\\\C"));
        assert!(e.ends_with("\\n"));
        assert!(!e.contains('\n')); // literal newline must be encoded
    }

    #[test]
    fn snippet_wrappers_contain_banner() {
        let painted = "AB\n";
        assert!(wrap(Format::Rust, painted).contains("pub const BANNER"));
        assert!(wrap(Format::Go, painted).contains("const Banner"));
        assert!(wrap(Format::Python, painted).contains("BANNER ="));
        let sh = wrap(Format::Shell, painted);
        assert!(sh.contains("<<'SIGIL_BANNER'"));
        assert!(sh.contains("AB\n"));
    }

    #[test]
    fn passthrough_formats_unchanged() {
        let painted = "hello\n";
        assert_eq!(wrap(Format::Raw, painted), painted);
        assert_eq!(wrap(Format::Ansi, painted), painted);
        assert_eq!(wrap(Format::Term, painted), painted);
    }
}
