//! Output formats: emit a rendered banner as terminal output, raw text, or a
//! ready-to-paste snippet for another language.
//!
//! The snippet formats let you generate a banner once and embed it directly in
//! your own tool's source — a splash for `--help`, a startup logo, etc.

/// A target output format for a rendered banner.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Format {
    /// Colored terminal output (color auto-detected: on for a TTY, off when piped).
    Term,
    /// Raw ANSI string, color forced on — for capturing colored bytes.
    Ansi,
    /// Plain glyphs, no color.
    Raw,
    /// A Rust `const` snippet.
    Rust,
    /// A Go `const` snippet.
    Go,
    /// A Python string snippet.
    Python,
    /// A JavaScript `const` snippet.
    JavaScript,
    /// A TypeScript `const` snippet.
    TypeScript,
    /// A C `static const char *` snippet.
    C,
    /// A C++ `inline constexpr` snippet.
    Cpp,
    /// A Ruby constant snippet.
    Ruby,
    /// A POSIX shell heredoc snippet.
    Shell,
    /// A standalone SVG image.
    Svg,
    /// A standalone HTML document (a `<pre>` of colored spans).
    Html,
    /// A PNG raster image.
    Png,
    /// A JSON description of the grid.
    Json,
}

impl Format {
    pub fn parse(s: &str) -> Result<Format, String> {
        match s.to_ascii_lowercase().as_str() {
            "term" | "terminal" => Ok(Format::Term),
            "ansi" => Ok(Format::Ansi),
            "raw" | "text" | "txt" => Ok(Format::Raw),
            "rust" | "rs" => Ok(Format::Rust),
            "go" | "golang" => Ok(Format::Go),
            "python" | "py" => Ok(Format::Python),
            "js" | "javascript" | "node" => Ok(Format::JavaScript),
            "ts" | "typescript" => Ok(Format::TypeScript),
            "c" => Ok(Format::C),
            "cpp" | "c++" | "cxx" | "cc" => Ok(Format::Cpp),
            "ruby" | "rb" => Ok(Format::Ruby),
            "shell" | "sh" | "bash" => Ok(Format::Shell),
            "svg" => Ok(Format::Svg),
            "html" | "htm" => Ok(Format::Html),
            "png" => Ok(Format::Png),
            "json" => Ok(Format::Json),
            _ => Err(format!(
                "unknown format: {s} \
                 (term|ansi|raw|rust|go|python|js|ts|c|cpp|ruby|shell|svg|html|png|json)"
            )),
        }
    }

    /// Whether this format bakes color into its output regardless of TTY.
    pub fn forces_color(self) -> bool {
        matches!(self, Format::Ansi) || self.is_snippet()
    }

    /// Whether this format is a code/text snippet (vs. direct terminal output).
    pub fn is_snippet(self) -> bool {
        matches!(
            self,
            Format::Rust
                | Format::Go
                | Format::Python
                | Format::JavaScript
                | Format::TypeScript
                | Format::C
                | Format::Cpp
                | Format::Ruby
                | Format::Shell
        )
    }
}

/// Wrap a painted banner in the chosen snippet format. For non-snippet formats
/// (`Term`, `Ansi`, `Raw`) the painted string is returned unchanged.
///
/// When `func` is set, snippet formats emit a ready-to-call `print_banner`
/// function instead of a bare constant; it has no effect on non-snippet formats.
pub fn wrap(format: Format, painted: &str, func: bool) -> String {
    if func && format.is_snippet() {
        return wrap_func(format, painted);
    }
    match format {
        // Svg/Html/Png/Json are rendered separately (not from painted ANSI).
        Format::Term
        | Format::Ansi
        | Format::Raw
        | Format::Svg
        | Format::Html
        | Format::Png
        | Format::Json => painted.to_string(),
        Format::Rust => format!(
            "// Generated by sigil. Print with: print!(\"{{BANNER}}\");\n\
             pub const BANNER: &str = \"{}\";\n",
            escape_c_like(painted)
        ),
        Format::Go => format!(
            "// Generated by sigil. Print with: fmt.Print(Banner)\n\
             const Banner = \"{}\"\n",
            escape_c_like(painted)
        ),
        Format::Python => format!(
            "# Generated by sigil. Print with: print(BANNER, end=\"\")\n\
             BANNER = \"{}\"\n",
            escape_c_like(painted)
        ),
        Format::JavaScript => format!(
            "// Generated by sigil. Print with: process.stdout.write(BANNER)\n\
             export const BANNER = \"{}\";\n",
            escape_c_like(painted)
        ),
        Format::TypeScript => format!(
            "// Generated by sigil. Print with: process.stdout.write(BANNER)\n\
             export const BANNER: string = \"{}\";\n",
            escape_c_like(painted)
        ),
        Format::C => format!(
            "/* Generated by sigil. Print with: fputs(BANNER, stdout); */\n\
             static const char *BANNER = \"{}\";\n",
            escape_c_like(painted)
        ),
        Format::Cpp => format!(
            "// Generated by sigil. Print with: std::cout << BANNER;\n\
             inline constexpr const char *BANNER = \"{}\";\n",
            escape_c_like(painted)
        ),
        Format::Ruby => format!(
            "# Generated by sigil. Print with: print BANNER\n\
             BANNER = \"{}\"\n",
            escape_ruby(painted)
        ),
        Format::Shell => format!(
            "# Generated by sigil. Prints a banner (contains ANSI color codes).\n\
             cat <<'SIGIL_BANNER'\n{}SIGIL_BANNER\n",
            painted
        ),
    }
}

/// Emit a self-contained `print_banner` function for a snippet format.
///
/// Only called for snippet formats (guarded by `wrap`); the banner literal is
/// baked in, so the function needs no arguments.
fn wrap_func(format: Format, painted: &str) -> String {
    let lit = escape_c_like(painted);
    match format {
        Format::Rust => format!(
            "// Generated by sigil.\npub fn print_banner() {{\n    print!(\"{lit}\");\n}}\n"
        ),
        Format::Go => format!(
            "// Generated by sigil. Requires: import \"fmt\"\n\
             func PrintBanner() {{\n\tfmt.Print(\"{lit}\")\n}}\n"
        ),
        Format::Python => {
            format!("# Generated by sigil.\ndef print_banner():\n    print(\"{lit}\", end=\"\")\n")
        }
        Format::JavaScript => format!(
            "// Generated by sigil.\n\
             export function printBanner() {{\n  process.stdout.write(\"{lit}\");\n}}\n"
        ),
        Format::TypeScript => format!(
            "// Generated by sigil.\n\
             export function printBanner(): void {{\n  process.stdout.write(\"{lit}\");\n}}\n"
        ),
        Format::C => format!(
            "/* Generated by sigil. */\n#include <stdio.h>\n\
             static void print_banner(void) {{\n    fputs(\"{lit}\", stdout);\n}}\n"
        ),
        Format::Cpp => format!(
            "// Generated by sigil.\n#include <iostream>\n\
             inline void print_banner() {{\n    std::cout << \"{lit}\";\n}}\n"
        ),
        Format::Ruby => format!(
            "# Generated by sigil.\ndef print_banner\n  print \"{}\"\nend\n",
            escape_ruby(painted)
        ),
        Format::Shell => format!(
            "# Generated by sigil.\n\
             print_banner() {{\n  cat <<'SIGIL_BANNER'\n{painted}SIGIL_BANNER\n}}\n"
        ),
        // Non-snippet formats never reach here (guarded in `wrap`).
        _ => painted.to_string(),
    }
}

/// Escape a string for a double-quoted C-like literal (Rust/Go/Python).
///
/// Keeps printable Unicode (block glyphs, box drawing) literal; encodes the
/// escape byte, quotes, backslashes, and newlines.
fn escape_c_like(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 16);
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\x1b' => out.push_str("\\x1b"),
            c => out.push(c),
        }
    }
    out
}

/// Escape a string for a double-quoted Ruby literal.
///
/// Same as [`escape_c_like`], but also escapes `#` so a `#{...}` / `#@` / `#$`
/// in the banner content can't trigger string interpolation.
fn escape_ruby(s: &str) -> String {
    escape_c_like(s).replace('#', "\\#")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_aliases() {
        assert_eq!(Format::parse("rs").unwrap(), Format::Rust);
        assert_eq!(Format::parse("PY").unwrap(), Format::Python);
        assert_eq!(Format::parse("bash").unwrap(), Format::Shell);
        assert_eq!(Format::parse("javascript").unwrap(), Format::JavaScript);
        assert_eq!(Format::parse("TS").unwrap(), Format::TypeScript);
        assert_eq!(Format::parse("c++").unwrap(), Format::Cpp);
        assert_eq!(Format::parse("rb").unwrap(), Format::Ruby);
        assert!(Format::parse("cobol").is_err());
    }

    #[test]
    fn new_snippet_wrappers_emit_literals() {
        let painted = "AB\n";
        assert!(wrap(Format::JavaScript, painted, false).contains("export const BANNER ="));
        assert!(wrap(Format::TypeScript, painted, false).contains("BANNER: string ="));
        assert!(wrap(Format::C, painted, false).contains("static const char *BANNER"));
        assert!(wrap(Format::Cpp, painted, false).contains("constexpr"));
        assert!(wrap(Format::Ruby, painted, false).contains("BANNER ="));
        // Every new snippet bakes color in and counts as a snippet.
        for f in [
            Format::JavaScript,
            Format::TypeScript,
            Format::C,
            Format::Cpp,
            Format::Ruby,
        ] {
            assert!(f.is_snippet());
            assert!(f.forces_color());
        }
    }

    #[test]
    fn ruby_escapes_interpolation() {
        // A literal "#{" in the banner must not become Ruby interpolation.
        let out = wrap(Format::Ruby, "a#{b}\n", false);
        assert!(out.contains("\\#{b}"));
    }

    #[test]
    fn func_emits_a_callable_function() {
        let painted = "AB\n";
        assert!(wrap(Format::Rust, painted, true).contains("pub fn print_banner()"));
        assert!(wrap(Format::Python, painted, true).contains("def print_banner():"));
        assert!(wrap(Format::JavaScript, painted, true).contains("export function printBanner()"));
        assert!(wrap(Format::Cpp, painted, true).contains("void print_banner()"));
        assert!(wrap(Format::Shell, painted, true).contains("print_banner() {"));
        // --func is a no-op for non-snippet formats.
        assert_eq!(wrap(Format::Raw, painted, true), painted);
    }

    #[test]
    fn escapes_ansi_and_quotes() {
        let painted = "\x1b[38;2;1;2;3mA\"B\\C\x1b[0m\n";
        let e = escape_c_like(painted);
        assert!(e.contains("\\x1b[38;2;1;2;3m"));
        assert!(e.contains("A\\\"B\\\\C"));
        assert!(e.ends_with("\\n"));
        assert!(!e.contains('\n')); // literal newline must be encoded
    }

    #[test]
    fn snippet_wrappers_contain_banner() {
        let painted = "AB\n";
        assert!(wrap(Format::Rust, painted, false).contains("pub const BANNER"));
        assert!(wrap(Format::Go, painted, false).contains("const Banner"));
        assert!(wrap(Format::Python, painted, false).contains("BANNER ="));
        let sh = wrap(Format::Shell, painted, false);
        assert!(sh.contains("<<'SIGIL_BANNER'"));
        assert!(sh.contains("AB\n"));
    }

    #[test]
    fn passthrough_formats_unchanged() {
        let painted = "hello\n";
        assert_eq!(wrap(Format::Raw, painted, false), painted);
        assert_eq!(wrap(Format::Ansi, painted, false), painted);
        assert_eq!(wrap(Format::Term, painted, false), painted);
    }
}
